kind = "web"
previewPath = "/"
title = "Jojo Collections"
version = "1.0.0"
id = "artifacts/jojo-collections"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18316

[services.development]
run = "pnpm --filter @workspace/jojo-collections run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jojo-collections", "run", "build" ]
publicDir = "artifacts/jojo-collections/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18316"
BASE_PATH = "/"
